server:
  listenAddress: "localhost"
  port: 3000
  debug: true
  features:
    - CIP-1694
dbSync:
  host: "cdbsync-dev.mydomain.com"
  port: 5432
  user: "cdbsync"
  database: "cdbsync"
  maxConnections: 10
network: "mainnet"
tokenRegistryUrl: "https://tokens.cardano.org"
mithril:
  enabled: true
  aggregator: "https://aggregator.release-mainnet.api.mithril.network/aggregator"
